backend:
  name: github
  repo: amaanrmajidi/testdocs # Replace with your actual GitHub username/repo
  branch: main # or master, depending on your default branch

local_backend: true # For local development

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "docs"
    label: "User Documentation"
    folder: "content/docs"
    create: true
    format: "frontmatter"
    extension: "mdx"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

